### ISSUE TITLE
Listing associations/cascading within collection scope only displaying mappings from underlying source

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1240]
Select concept 163310 here:
https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/collections/test1/v1.0/

There are 4 mappings & target concepts in the collection for this from-concept 163310, however only 3 are shown. The 3 that are shown are the original 3 from the underlying CIEL source. In the collection, a new mapping was created to associate 163310 with CIEL:163723 In Progress, but this is not showing up in the mappings list.

**Comment by snyaggarwal** [comment]
@paynejd this bug should be fixed now after deployment to Staging. Can you please recheck and confirm.

**Comment by paynejd** [comment]
Tested this on staging and the issue is still there -- see this screenshot for an example -- HIV Viral Load Status has 3 "Q-AND-A" mappings defined in the CIEL source (which is all that is shown in the TermBrowser). However, it should be viewing this in the context of the collection, which defines an additional Q-AND-A mapping, so there should be 4 in the screenshot.

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/1189689/158606034-f11a51d9-40ff-4492-ac9f-de07c3d4cabc.png">

**Comment by snyaggarwal** [comment]
@paynejd the 4th mapping version thats not showing is because that mapping version is showing from/to concepts as not linked (not in OCL), that bug was fixed.
If you recreate the scenario, it should work well.

**Comment by snyaggarwal** [comment]
@paynejd Can we close this?

**Comment by paynejd** [comment]
https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/collections/test1/v1.0/

Hi Sunny- I opened up concept `163310` again at the above link and it showed 5 associations under concept details when it should have shown 6. (See first 2 screenshots below.) Is it possible that it's an indexing issue?

Just in case, I generated a new expansion here (https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/collections/test1/v1.0/expansions/trying-again/) -- and then went to the Concepts tab, opened up concept details for 163310, and then I received a 404 (see the 3rd screenshot below)

<img width="527" alt="image" src="https://user-images.githubusercontent.com/1189689/169328019-d66ddd74-2166-49e1-bbe2-fe1dd3c4063c.png">

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/1189689/169327920-502f7e3d-2400-4c90-8d09-469f7be83e2f.png">

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/1189689/169328740-773feb8b-7e21-46d6-a005-ede48bc310dc.png">

**Comment by snyaggarwal** [comment]
@paynejd 404 might be because it was still computing expansion asynchronously.
I opened the expansion you created -- https://app.staging.openconceptlab.org/#/orgs/OpenmrsTest/collections/test1/v1.0/expansions/trying-again/
and its showing correct 6 mappings

**Comment by paynejd** [comment]
Can we show some different info to the user if an expansion is being
processed? Isnt the status code for still processing like a 303?

**Comment by jamlung-ri** [comment]
@paynejd Please review and, if applicable, close this ticket or remove it from the Oct. 5 sprint.
