### ISSUE TITLE
Map type with candidates

### ISSUE THREAD

**Issue by michaelbontyes** [OpenConceptLab/ocl_issues#2154]
The selection of the map type in top 5 candidates is buggy. Selecting a map type for one concept currently affects all candidates + it doesn't always update the top 1 to be approved. 

Expected behavior would be to:
- [x] Selecting the **map type for 1 concept** should not update the map type of other candidates
- [x] Clicking on one of the candidates to select it should move it to **approved**

**Comment by snyaggarwal** [comment]
@michaelbontyes This should be fixed now

**Comment by michaelbontyes** [comment]
@snyaggarwal the map type of all candidates is still getting updated when going from 1 tab to the other:

https://github.com/user-attachments/assets/ea0e6e9e-225e-4a52-b568-8ad71c53a969

**Comment by snyaggarwal** [comment]
@michaelbontyes this is now fixed

**Comment by paynejd** [comment]
@michaelbontyes @snyaggarwal We can close this now that map type selection has moved out of the candidates list?

**Comment by michaelbontyes** [comment]
I agree, we can close this one as it was solved.
