### ISSUE TITLE
Deleting reference not cascading as expected in API v2

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#599]
While testing the OCL for OpenMRS client against OCL API v2 on QA, I noticed that I couldn't remove a concept from a collection. After inspecting the API calls involved, it appears that a request like this:

```
curl 'https://api.qa.aws.openconceptlab.org/users/test/collections/test1/references/?cascade=sourcemappings' \
  -X 'DELETE' \
  -H 'authorization: Token <ocl api token>' \
  -H 'content-type: application/json;charset=UTF-8' \
  --data-raw '{"references":["/orgs/CIEL/sources/CIEL/concepts/10/44641/"]}'
```

deletes the reference (slowly, taking ~8s), but does not cascade as expected. After deleting the reference, this request:

```
curl 'https://api.qa.aws.openconceptlab.org/users/test/collections/test1/concepts/'
```

still shows the concept (`id = 10`) in the list of concepts for the collection:

```json
  ...,
  {
    "uuid": "44641",
    "id": "10",
    "external_id": "10AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "concept_class": "Diagnosis",
    "datatype": "N/A",
    "url": "/orgs/CIEL/sources/CIEL/concepts/10/",
    "retired": false,
    "source": "CIEL",
    "owner": "CIEL",
    "owner_type": "Organization",
    "owner_url": "/orgs/CIEL/",
    "display_name": "Acute bronchitis",
    "display_locale": "en",
    "version": "44641",
    "update_comment": null,
    "locale": null,
    "version_created_by": "ocladmin",
    "version_created_on": "2021-01-17T03:20:34.231051Z",
    "mappings": [],
    "is_latest_version": true,
    "versions_url": "/orgs/CIEL/sources/CIEL/concepts/10/versions/",
    "version_url": "/orgs/CIEL/sources/CIEL/concepts/10/44641/"
  },
  ...
```

I believe the `?cascade=sourcemappings` parameter within the original `DELETE` request should not only remove the reference, but also remove any concepts or mappings.

**Comment by askanter** [comment]
Cascading delete should only delete concepts which are not part of another concept set/answer. External mappings which are not mapped to dependent concepts can be deleted.

**Comment by bmamlin** [comment]
> Cascading delete should only delete concepts which are not part of another concept set/answer. External mappings which are not mapped to dependent concepts can be deleted.

@askanter, so if I try to remove a concept from a collection that is used as an answer or set member, you're suggesting I would get an error stating the the concept is used by another concept and, therefore cannot be deleted? Then that would apply to deletes as well as cascading deletes, right?

@snyaggarwal, to be clear, the bug hear is that deletes do not appear to be cascading at all – i.e., removing a concept from a collection deletes the references without deleting the actual concept from the collection (even when there are no conflicts).

**Comment by snyaggarwal** [comment]
@bmamlin The fix is deployed to correctly delete references.

**Comment by bmamlin** [comment]
I'm still having issues deleting. Perhaps the collection is in an unsupported state now?

In user `test`'s `test1` collection on QA, Acute Bronchitis (`CIEL 10`) is included in the list of concepts:

```
curl 'https://api.qa.aws.openconceptlab.org/users/test/collections/test1/concepts/'
```

but isn't in the list of references:

```
curl 'https://api.qa.aws.openconceptlab.org/users/test/collections/test1/references/'
```

The effect in the client is that I see "Acute Bronchitis" (`CIEL 10`) in the [list of concepts for the collection](https://openmrs.qa2.openconceptlab.org/users/test/collections/test1/concepts/?page=1&q=), but when I delete "Acute Bronchitis" and refresh the screen, it reappears (I can't get rid of it).

Some other concepts (e.g., "Unknown" `CIEL 1067`) appears to show same behavior (concept appears to be deleted, but after refreshing the page it comes back); maybe I tried deleting those earlier as well?

**Comment by snyaggarwal** [comment]
@bmamlin There were some fixes made on collections-children relations based on couple of earlier bugs. That may have caused this collection in an uncertain state. Can you create a new collection and test things on that?
