### ISSUE TITLE
Collection exports only include concepts, no mappings

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#604]
I am retrieving collection exports from OCL that contain all of the concepts in the collection, but none of the concepts. This appears to only happen with the auto-generated export. When I manually `DELETE` the export and recreate it with a `POST`, the export includes both the concepts and mappings.

For example, here is the export with empty mappings:
https://api.staging.aws.openconceptlab.org/orgs/DATIM-MOH-demojp-FY19/collections/PMTCT-ART-N-MOH-HllvX50cXC0/FY19.v0/export/

And here are the mappings correctly returned by the API:
https://api.staging.aws.openconceptlab.org/orgs/DATIM-MOH-demojp-FY19/collections/PMTCT-ART-N-MOH-HllvX50cXC0/FY19.v0/mappings/

**Comment by snyaggarwal** [comment]
Fixed

**Comment by paynejd** [comment]
I tested this on staging.aws and performance was **way** better (the exports were available almost immediately), however the error still occurred -- mappings were missing from the exports. When I deleted an export and recreated it, the mappings were then available in the export.

**Comment by snyaggarwal** [comment]
@paynejd @rkorytkowski 
Exports on version creation should now be even faster. Made the following changes (and tested on staging):
1. Add processing tag.
2. Copy concepts/mappings to the new version in DB only.
3. Queue export version task (this doesn't use ES)
4. index copied concepts/mappings (in bulk-parallel)
5. Remove processing flag.

**Comment by paynejd** [comment]
This is now working great!
